/**
 * resolve-py/stdlib.ts — Phase 4b T321 — Python stdlib allowlist.
 *
 * Hardcoded set of Python 3.11 standard-library top-level modules. Sourced from
 * CPython's `sys.stdlib_module_names` (Python 3.11.x). For dotted imports like
 * `urllib.request` or `email.mime.text`, only the leading segment is checked
 * (`urllib`, `email`).
 *
 * Specifiers that match return `kind: 'builtin'` from the dispatcher — mirroring
 * the `node:` prefix handling for Node/Bun built-ins. The graph layer treats
 * `'builtin'` like `'external'` but with `resolvable: true`, so import-hygiene
 * and unused-deps rules don't false-positive on stdlib usage.
 *
 * The set is frozen for determinism. Additions for future Python versions
 * should land as a separate set + version-aware accessor; v1 targets 3.11+.
 *
 * Note on private modules: CPython's `sys.stdlib_module_names` includes both
 * public modules (e.g. `os`) and underscore-prefixed internal modules (`_abc`,
 * `_thread`). User code may legitimately import some of the underscore ones
 * (`_thread`, `_csv`, `_decimal`), so we keep them in the allowlist. Frozen
 * implementation modules under `_frozen_importlib` are NOT user-facing and
 * are excluded.
 */

/**
 * Python 3.11 standard-library top-level module names. Verbatim from
 * `sys.stdlib_module_names` minus internal `_frozen_*` entries.
 */
export const PYTHON_STDLIB_MODULES: ReadonlySet<string> = Object.freeze(
  new Set<string>([
    '__future__',
    '_abc',
    '_aix_support',
    '_ast',
    '_asyncio',
    '_bisect',
    '_blake2',
    '_bootsubprocess',
    '_bz2',
    '_codecs',
    '_codecs_cn',
    '_codecs_hk',
    '_codecs_iso2022',
    '_codecs_jp',
    '_codecs_kr',
    '_codecs_tw',
    '_collections',
    '_collections_abc',
    '_compat_pickle',
    '_compression',
    '_contextvars',
    '_csv',
    '_ctypes',
    '_curses',
    '_curses_panel',
    '_datetime',
    '_decimal',
    '_elementtree',
    '_functools',
    '_hashlib',
    '_heapq',
    '_imp',
    '_io',
    '_json',
    '_locale',
    '_lsprof',
    '_lzma',
    '_markupbase',
    '_md5',
    '_multibytecodec',
    '_multiprocessing',
    '_opcode',
    '_operator',
    '_osx_support',
    '_overlapped',
    '_pickle',
    '_posixshmem',
    '_posixsubprocess',
    '_py_abc',
    '_pydecimal',
    '_pyio',
    '_queue',
    '_random',
    '_sha1',
    '_sha256',
    '_sha3',
    '_sha512',
    '_signal',
    '_sitebuiltins',
    '_socket',
    '_sqlite3',
    '_sre',
    '_ssl',
    '_stat',
    '_statistics',
    '_string',
    '_strptime',
    '_struct',
    '_symtable',
    '_thread',
    '_threading_local',
    '_tkinter',
    '_tokenize',
    '_tracemalloc',
    '_typing',
    '_uuid',
    '_warnings',
    '_weakref',
    '_weakrefset',
    '_winapi',
    '_zoneinfo',
    'abc',
    'aifc',
    'antigravity',
    'argparse',
    'array',
    'ast',
    'asynchat',
    'asyncio',
    'asyncore',
    'atexit',
    'audioop',
    'base64',
    'bdb',
    'binascii',
    'bisect',
    'builtins',
    'bz2',
    'cProfile',
    'calendar',
    'cgi',
    'cgitb',
    'chunk',
    'cmath',
    'cmd',
    'code',
    'codecs',
    'codeop',
    'collections',
    'colorsys',
    'compileall',
    'concurrent',
    'configparser',
    'contextlib',
    'contextvars',
    'copy',
    'copyreg',
    'crypt',
    'csv',
    'ctypes',
    'curses',
    'dataclasses',
    'datetime',
    'dbm',
    'decimal',
    'difflib',
    'dis',
    'distutils',
    'doctest',
    'email',
    'encodings',
    'ensurepip',
    'enum',
    'errno',
    'faulthandler',
    'fcntl',
    'filecmp',
    'fileinput',
    'fnmatch',
    'fractions',
    'ftplib',
    'functools',
    'gc',
    'genericpath',
    'getopt',
    'getpass',
    'gettext',
    'glob',
    'graphlib',
    'grp',
    'gzip',
    'hashlib',
    'heapq',
    'hmac',
    'html',
    'http',
    'idlelib',
    'imaplib',
    'imghdr',
    'imp',
    'importlib',
    'inspect',
    'io',
    'ipaddress',
    'itertools',
    'json',
    'keyword',
    'lib2to3',
    'linecache',
    'locale',
    'logging',
    'lzma',
    'mailbox',
    'mailcap',
    'marshal',
    'math',
    'mimetypes',
    'mmap',
    'modulefinder',
    'msilib',
    'msvcrt',
    'multiprocessing',
    'netrc',
    'nis',
    'nntplib',
    'nt',
    'ntpath',
    'numbers',
    'opcode',
    'operator',
    'optparse',
    'os',
    'ossaudiodev',
    'pathlib',
    'pdb',
    'pickle',
    'pickletools',
    'pipes',
    'pkgutil',
    'platform',
    'plistlib',
    'poplib',
    'posix',
    'posixpath',
    'pprint',
    'profile',
    'pstats',
    'pty',
    'pwd',
    'py_compile',
    'pyclbr',
    'pydoc',
    'pydoc_data',
    'pyexpat',
    'queue',
    'quopri',
    'random',
    're',
    'readline',
    'reprlib',
    'resource',
    'rlcompleter',
    'runpy',
    'sched',
    'secrets',
    'select',
    'selectors',
    'shelve',
    'shlex',
    'shutil',
    'signal',
    'site',
    'smtpd',
    'smtplib',
    'sndhdr',
    'socket',
    'socketserver',
    'spwd',
    'sqlite3',
    'sre_compile',
    'sre_constants',
    'sre_parse',
    'ssl',
    'stat',
    'statistics',
    'string',
    'stringprep',
    'struct',
    'subprocess',
    'sunau',
    'symtable',
    'sys',
    'sysconfig',
    'syslog',
    'tabnanny',
    'tarfile',
    'telnetlib',
    'tempfile',
    'termios',
    'textwrap',
    'this',
    'threading',
    'time',
    'timeit',
    'tkinter',
    'token',
    'tokenize',
    'tomllib',
    'trace',
    'traceback',
    'tracemalloc',
    'tty',
    'turtle',
    'turtledemo',
    'types',
    'typing',
    'unicodedata',
    'unittest',
    'urllib',
    'uu',
    'uuid',
    'venv',
    'warnings',
    'wave',
    'weakref',
    'webbrowser',
    'winreg',
    'winsound',
    'wsgiref',
    'xdrlib',
    'xml',
    'xmlrpc',
    'zipapp',
    'zipfile',
    'zipimport',
    'zlib',
    'zoneinfo',
  ]),
);

/**
 * Return `true` if `specifier` (or its leading dotted segment) is a Python
 * stdlib module. Returns `false` for empty input.
 *
 *   isPythonStdlib('os')           → true
 *   isPythonStdlib('os.path')      → true
 *   isPythonStdlib('urllib.request') → true
 *   isPythonStdlib('requests')     → false
 *   isPythonStdlib('')             → false
 */
export function isPythonStdlib(specifier: string): boolean {
  if (specifier === '') return false;
  // Relative imports (leading dots) are never stdlib.
  if (specifier.startsWith('.')) return false;
  const dot = specifier.indexOf('.');
  const head = dot === -1 ? specifier : specifier.slice(0, dot);
  return PYTHON_STDLIB_MODULES.has(head);
}
